### ISSUE TITLE
EL results

### ISSUE THREAD

**Issue by GSidiropoulos** [wudapeng268/KBQA-Adapter#1]
Dear Peng,

I was wondering if you could please provide the entity linking results from FocusPrune after they are mapped to Freebase, because if I understood correctly from your code, you use the ground truth entity to measure the KBQA accuracy.

Best regards,
Georgios

**Comment by wudapeng268** [comment]
Hi Georgios,

When measuring the KBQA accuracy, we use the entity after FocusPrune, you can see that we use .cand pickle file which is generated by KBQA-Baseline, to measuring KBQA accuracy. 

Thanks and Best
Peng Wu

**Comment by yhshu** [comment]
Dear Peng,
I also have the same issue here. FocusPrune has provided mentions, but I cannot see how it leads to a surface match method and the final entity results. I actually haven't seen the `.cand` pickle file. 
Would you please give more explanation about EL? Thanks a lot.
