### ISSUE TITLE
Several execution problems found

### ISSUE THREAD

**Issue by DENG-Yifan** [wudapeng268/KBQA-Adapter#3]
1. The paths in several py files are out-of-date. They can be found by searching  '/wup/'.
2. In qa+adapter/script/baseline, --key_num $i should be added to each line with python command.
3. In qa+adapter/start.py, the util.FileUtil cannot be imported until relative codes are written in qa+adapter/src/__init__.py and qa+adapter/src/util/__init__.py.
4. In qa+adapter/src/util/FileUtil.py, the write() function might not work for utf-8 is not explicitly designated. It is suggested to use io.open(file, 'w', encoding='utf-8') to open files.

These are not severe problems and some of which might be environment dependent. But I just list them here.
At last, thank you for your work and codes!

**Comment by wudapeng268** [comment]
Thanks for your comment. I'll update the code later.
