### ISSUE TITLE
network.py中adapter的input和target是相同的，请问这是为什么呢？

### ISSUE THREAD

**Issue by lbda1** [wudapeng268/KBQA-Adapter#5]
global_emb = tf.constant(self.load_relation_emb(self.transX_embedding_path), dtype=tf.float32,name="relation_part_embedding")

self.rel_embedding = tf.Variable(self.load_relation_emb(self.transX_embedding_path), trainable=self.fine_tune_part_emb, name="relation_part_embedding")

self.relation_adapter = adapter(global_emb, self.rel_embedding, self.adapter_keep_prob,self.relation_index[:, 0], "relation")

Adapter中input和target是相同的，请问这是为什么呢？

**Comment by wudapeng268** [comment]
input 仅仅用作初始化，随训练过程中更改，target是固定的。所以训练结束是不同的。
